In [ ]:
import pandas as pd

In [3]:
print("hello world")

hello world

In [2]:
import sys
print(sys.executable)

c:\Users\USER\Desktop\Folder\venv\Scripts\python.exe

In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
df = pd.read_csv("data/sales.csv")

In [3]:
df

         Date Product       City  Quantity  Revenue
0  2026-08-01  Laptop     Lahore         2   200000
1  2026-08-02   Phone    Karachi         5   150000
2  2026-08-03  Laptop     Lahore         1   100000
3  2026-08-04  Tablet  Islamabad         3    90000
4  2026-08-05   Phone     Lahore         4   120000
5  2026-08-06  Laptop    Karachi         2   200000
6  2026-08-07  Tablet     Lahore         2    60000

In [4]:
df.shape

(7, 5)

In [5]:
df.columns

Index(['Date', 'Product', 'City', 'Quantity', 'Revenue'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      7 non-null      str
 1   Product   7 non-null      str
 2   City      7 non-null      str
 3   Quantity  7 non-null      int64
 4   Revenue   7 non-null      int64
dtypes: int64(2), str(3)
memory usage: 412.0 bytes

In [7]:
df["Revenue"]

0    200000
1    150000
2    100000
3     90000
4    120000
5    200000
6     60000
Name: Revenue, dtype: int64

In [8]:
df["Product"]

0    Laptop
1     Phone
2    Laptop
3    Tablet
4     Phone
5    Laptop
6    Tablet
Name: Product, dtype: str

In [10]:
total_revenue = df["Revenue"].sum()

print(total_revenue)

920000

In [11]:
average_revenue = df["Revenue"].mean()

print(average_revenue)

131428.57142857142

In [12]:
df["Revenue"].max()

np.int64(200000)

In [13]:
df["Revenue"].min()

np.int64(60000)

In [14]:
df[df["City"] == "Lahore"]

         Date Product    City  Quantity  Revenue
0  2026-08-01  Laptop  Lahore         2   200000
2  2026-08-03  Laptop  Lahore         1   100000
4  2026-08-05   Phone  Lahore         4   120000
6  2026-08-07  Tablet  Lahore         2    60000

In [15]:
df[df["City"] == "Karachi"]

         Date Product     City  Quantity  Revenue
1  2026-08-02   Phone  Karachi         5   150000
5  2026-08-06  Laptop  Karachi         2   200000

In [16]:
df[df["Product"] == "Laptop"]

         Date Product     City  Quantity  Revenue
0  2026-08-01  Laptop   Lahore         2   200000
2  2026-08-03  Laptop   Lahore         1   100000
5  2026-08-06  Laptop  Karachi         2   200000

In [17]:
df.groupby("City")["Revenue"].sum()

City
Islamabad     90000
Karachi      350000
Lahore       480000
Name: Revenue, dtype: int64

In [18]:
df[df["City"] == "Lahore"]["Revenue"].sum()

np.int64(480000)

In [19]:
df.groupby("Product")["Revenue"].sum()

Product
Laptop    500000
Phone     270000
Tablet    150000
Name: Revenue, dtype: int64